<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'rotas' => $baseDir . '/model/rotas.class.php',
    'template' => $baseDir . '/model/template.class.php',
);
